### ISSUE TITLE
 './data' file directry not found

### ISSUE THREAD

**Issue by DimalChathuranga** [neftlon/af2-plddt-contextualized#2]
Traceback (most recent call last):
  File "/content/af2-plddt-contextualized/./scripts/neff_gpu.py", line 102, in <module>
    main()
  File "/content/af2-plddt-contextualized/./scripts/neff_gpu.py", line 82, in main
    infile = sys.stdin if args.INFILE == "-" else open(args.INFILE)
FileNotFoundError: [Errno 2] No such file or directory: './data/A0A0A0MRZ7.a3m'

I could not found './data' file directry

**Comment by johannes-spies** [comment]
I assume you cloned the repository and ran the example script without having a data directory. The example assumes that you have a directory present where you store your MSAs, in this case, `data/`. However, it is not required that you store your MSAs in that directory; you can use an arbitrary path to point to a `.a3m` file of your choice.

You can generate an MSA, for instance, with [mmseqs2](https://mmseqs.com/).

Feel free to reopen the issue if you have further questions.
